//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generation_Zero_Save_File_Modder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generation_Zero_Save_File_Modder.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_crown {
            get {
                object obj = ResourceManager.GetObject("_1_crown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _13 {
            get {
                object obj = ResourceManager.GetObject("_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _14 {
            get {
                object obj = ResourceManager.GetObject("_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _15 {
            get {
                object obj = ResourceManager.GetObject("_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16 {
            get {
                object obj = ResourceManager.GetObject("_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_crown {
            get {
                object obj = ResourceManager.GetObject("_2_crown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_crown {
            get {
                object obj = ResourceManager.GetObject("_3_crown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_crown {
            get {
                object obj = ResourceManager.GetObject("_4_crown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_crown {
            get {
                object obj = ResourceManager.GetObject("_5_crown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6_crown {
            get {
                object obj = ResourceManager.GetObject("_6_crown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8 {
            get {
                object obj = ResourceManager.GetObject("_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9 {
            get {
                object obj = ResourceManager.GetObject("_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatgevär 5 Extended Magazine,3359963809,3359963809,3359963809,3359963809,3359963809
        ///Automatgevär 4 Extended Magazine,3359963809,3359963809,3359963809,3359963809,3359963809
        ///AI-76 Extended Magazine,1727569198,3690786906,2145410535,1408373939,108980312
        ///Möller PP Extended Magazine,3520895500,588534837,2059699339,3842517818,735055802
        ///Klaucke 17 Extended Magazine,2790621325,256441433,4291300249,1302591039,3307898268
        ///Kvm 89 Extended Magazine,1521622499,2688710235,412216527,2285898363,2652884748
        ///Kvm 59 Ex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1122333116           ///1675447211           ///3599704378           ///3664930277           ///379411119           ///771308939           ///305283670           ///2690565765           ///4140177568           ///1716127143           ///2324315541           ///2191889410           ///1311760495           ///4205739798           ///2848224651           ///1110682342           ///2057493952           ///4217177927           ///1607570266           ///1414304607           ///1534462266           ///2956642606           ///4289341249           ///1017979386           ///2031994665           ///2394050693           ///1486077924           ///2699257751           ///1603432311           ///3088007515           ///3526088082           ///2739150939           ///1538348284           ///4203776870           ///2821703910           ///3317547883           ///250043317   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string itemHashes {
            get {
                return ResourceManager.GetString("itemHashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # char_part_pants_04_a &quot;Denim pants, dark blue&quot;        ///# char_part_hat_01_e &quot;Knit cap, dark green&quot;        ///# char_part_pants_09_c &quot;Short pleated skirt, blue/purple&quot;        ///# char_part_jacket_05_f &quot;Hip-hop jacket, green/white&quot;        ///# char_part_face_01_e &quot;Hoops, red&quot;        ///# char_part_shoes_01_e &quot;High top sneakers, light blue&quot;        ///# char_part_glasses_02_a &quot;Performance shades, gold&quot;        ///# char_part_shoes_02_h &quot;Leather shoes, purple&quot;        ///# char_part_jacket_02_a &quot;Windbreaker jacket, light blue&quot;        ///# char_part_hair_09_d &quot;Slicked back, bleach blond&quot;        ///# char_part [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string itemNames {
            get {
                return ResourceManager.GetString("itemNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1346744629
        ///3533383872
        ///582843454
        ///668653911
        ///718105477
        ///1810650845
        ///2981699539
        ///773355177
        ///396626412
        ///3496715869
        ///3686290408
        ///4242805379
        ///3212711861
        ///50410939 
        ///2695299762
        ///4167551889
        ///3032607371
        ///3129615105
        ///1753709842
        ///3795216219
        ///2187559362
        ///2764304095
        ///3038786482
        ///3596848579
        ///2808237727
        ///3443969574
        ///411326506
        ///3583340807
        ///1392519363
        ///4229843398
        ///1464365892
        ///3007313053
        ///2274122282
        ///2566776422
        ///2316367337
        ///3347452321
        ///3804470661
        ///239581900
        ///2669465353
        ///3314955553
        ///3231039701
        ///2519844724
        ///909746160
        ///1610969122
        ///3743871310
        ///909746160
        ///225284071
        ///717952 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möller PP,3055879776,2800125862,3155991537,1225959613,358135215,None
        ///Klaucke 17,1920462793,30913048,317912168,1158656473,1250828800,2290286314
        ///.44 Magnus,525713563,3669591716,1539616687,3654146736,4030765418,None
        ///12G Pump Action,3522570570,2946942083,400886324,1211181616,2270892881,1883785329
        ///Sjöqvist Semi-Auto,1668043928,3944939440,3723204762,1343436027,3777482652,None
        ///M/46 Kpist SMG,1438049323,2562218223,471434641,3343263738,1938906168,1734102884
        ///HP5,3329358393,1919634899,894785287,764274991,3995651 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WeaponIDs {
            get {
                return ResourceManager.GetString("WeaponIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möller PP
        ///Klaucke 17
        ///.44 Magnus
        ///12G Pump Action
        ///Sjöqvist Semi-Auto
        ///M/46 Kpist SMG
        ///HP5
        ///Meusser Hunting Rifle
        ///Älgstudsare Hunting Rifle
        ///Pansarvärnsgevär 90
        ///AI-76
        ///Automatgevär 4
        ///Automatgevär 5
        ///Granatgevär m/49
        ///Kvm 89 Squad Automatic Weapon
        ///Kvm 59 Machine Gun.
        /// </summary>
        internal static string WeaponNames {
            get {
                return ResourceManager.GetString("WeaponNames", resourceCulture);
            }
        }
    }
}
